name: bidi
description: Implementation of the BIDI algorithm, as described in http://www.unicode.org/reports/tr9/tr9-17.html.
version: 2.0.0+2
repository: https://github.com/xclud/dart_bidi
homepage: http://pwa.ir

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.0
  test: ^1.3.0
